include:
  - project: $CATALOG_PATH
    file:
      - vault-ci.yml
      - kaniko-ci.yml
      - helm-ci.yml
      - sonar-ci.yml
    ref: main

default:
  image: alpine:3.23.3

variables:
  REGISTRY_URL: ${REGISTRY_HOST}/${PROJECT_PATH}
  CHARTS_DIR: ./helm

stages:
  - read-secret
  - docker-build
  - helm-package

read_secret:
  stage: read-secret
  extends: .vault:read_secret

docker-build-docs:
  stage: docker-build
  extends: .kaniko:build-push
  variables:
    WORKING_DIR: .
    DOCKERFILE: ./Dockerfile
    IMAGE_NAMES: "mirai-api/docs:latest"

helm-package-push:
  stage: helm-package
  extends: .helm:build-push
  only:
    - tags
    - main
