apiVersion: v2
name: mirai-api
description: A Helm chart to deploy the MirAI API documentation site
type: application
keywords: []
home: https://github.com/IA-Generative/mirai-api
sources:
  - https://github.com/IA-Generative/mirai-api
dependencies: []
maintainers: []
# icon: A URL to an SVG or PNG image to be used as an icon (optional).
deprecated: false
annotations: {}
version: 1.0.0
appVersion: 1.0.0
