nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: false
  annotations: {}
  name: ''
imageCredentials:
  registry: ''
  username: ''
  password: ''
  email: ''
imagePullSecrets:
  - name: registry-pullsecret

docs:
  replicaCount: 1
  image:
    repository: ghcr.io/ia-generative/mirai-api/docs
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
  podAnnotations: {}
  podSecurityContext: {}
  # fsGroup: 2000
  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  container:
    port: 8080
    env: {}
    secrets: {}
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: mirai-nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: api.mirai.cpin.numerique-interieur.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: api.mirai.cpin.numerique-interieur.com-tls
        hosts:
          - api.mirai.cpin.numerique-interieur.com
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}
